ARG ROS_DISTRO=jazzy

FROM --platform=linux/arm64 ros:jazzy-ros-base

ENV DEBIAN_FRONTEND=noninteractive
ENV ROBOT_TYPE=WF_TRON1A

# # The base is outdated with respect to the ROS keyring - refresh it
# RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /tmp/ros.key \
#  && gpg --dearmor < /tmp/ros.key > /usr/share/keyrings/ros-archive-keyring.gpg \
#  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null \
#  && rm /tmp/ros.key

RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libwebsocketpp-dev \
    nlohmann-json3-dev \
    libmatio-dev \
    git \
    python3-rosdep \
    libapr1-dev \
    libaprutil1-dev \
    libpcl-dev \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    ros-jazzy-pcl-conversions \
    ros-jazzy-ament-cmake \
    ros-jazzy-slam-toolbox \
    ros-jazzy-nav2-bringup \
    ros-jazzy-navigation2 \
    ros-jazzy-xacro \
    ros-jazzy-rmw-cyclonedds-cpp \
    ros-jazzy-perception-pcl \
    ros-jazzy-pointcloud-to-laserscan \
    ros-dev-tools \
    ros-jazzy-laser-proc \
    python3-pip \
    nano \
    libasio-dev \
    kmod \
    iproute2 \
    can-utils \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /root/limx_ws/src

RUN git clone https://github.com/limxdynamics/limxsdk-lowlevel.git && \
    git clone https://github.com/limxdynamics/robot-description.git && \
    git clone --branch jazzy https://github.com/tu-darmstadt-ros-pkg/Livox-SDK2 /Livox-SDK2 && \
    git clone --branch jazzy https://github.com/tu-darmstadt-ros-pkg/livox_ros_driver2

# Clone and build Livox SDK2 (required for LiDAR driver)

# Livox SDK2
WORKDIR /Livox-SDK2
RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j$(nproc) && \
    make install"


# RUN /bin/bash -c "
#     rm -rf /usr/local/lib/liblivox_lidar_sdk_*
#     rm -rf /usr/local/include/livox_lidar_*
# "

# Livox ROS 2 driver
WORKDIR /root/limx_ws/src

RUN echo 'source /opt/ros/jazzy/setup.bash' >> /root/.bashrc && \
    echo 'source /root/limx_ws/install/setup.bash' >> /root/.bashrc && \
    echo 'export CMAKE_PREFIX_PATH="/usr/local:/opt/ros/jazzy:$CMAKE_PREFIX_PATH"' >> /root/.bashrc

# Build everything
WORKDIR /root/limx_ws
RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    export CMAKE_PREFIX_PATH=\"/usr/local:/opt/ros/jazzy:\$CMAKE_PREFIX_PATH\" && \
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release"

# Copy and build sdk_wrap
WORKDIR /root/limx_ws/src
COPY nodes/sdk_wrap sdk_wrap

WORKDIR /root/limx_ws
RUN /bin/bash -c "set -e && \
source /opt/ros/jazzy/setup.bash && \
source /root/limx_ws/install/setup.bash && \
export CMAKE_PREFIX_PATH=\"/usr/local:/opt/ros/jazzy:\$CMAKE_PREFIX_PATH\" && \
colcon build --symlink-install --packages-select=sdk_wrap --cmake-args -DCMAKE_BUILD_TYPE=Release"

RUN /bin/bash -c "rosdep install --rosdistro jazzy --from-paths src --ignore-src -r -y"

COPY config/ros_entrypoint.sh /ros_entrypoint.sh
COPY config/MID360_config.json /root/limx_ws/src/livox_ros_driver2/config/MID360_config.json
COPY config/msg_MID360_launch.py /root/limx_ws/src/livox_ros_driver2/launch/msg_MID360_launch.py

RUN chmod +x /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]