FROM osrf/ros:jazzy-desktop

ENV DEBIAN_FRONTEND=noninteractive
ENV ROBOT_TYPE=WF_TRON1A

RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libwebsocketpp-dev \
    nlohmann-json3-dev \
    libmatio-dev \
    git \
    python3-rosdep \
    libapr1-dev \
    libaprutil1-dev \
    ros-jazzy-xacro \
    ros-jazzy-pointcloud-to-laserscan \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/limx_ws/src

RUN git clone https://github.com/limxdynamics/limxsdk-lowlevel.git && \
    git clone https://github.com/limxdynamics/robot-description.git

# Clone and build Livox SDK2 (required for LiDAR driver)
RUN git clone --branch jazzy https://github.com/tu-darmstadt-ros-pkg/Livox-SDK2 /Livox-SDK2

# Livox SDK2
WORKDIR /Livox-SDK2
RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j$(nproc) && \
    make install"

# Livox ROS 2 driver
WORKDIR /root/limx_ws/src
RUN git clone --branch jazzy https://github.com/tu-darmstadt-ros-pkg/livox_ros_driver2

# Build everything
WORKDIR /root/limx_ws
RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    export CMAKE_PREFIX_PATH=\"/usr/local:\$CMAKE_PREFIX_PATH\" && \
    colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release"

RUN echo '#!/bin/bash\n\
set -e\n\
source /opt/ros/jazzy/setup.bash\n\
source /root/limx_ws/install/setup.bash\n\
exec "$@"' > /ros_entrypoint.sh && \
    chmod +x /ros_entrypoint.sh

RUN echo 'source /opt/ros/jazzy/setup.bash' >> /root/.bashrc && \
    echo 'source /root/limx_ws/install/setup.bash' >> /root/.bashrc


# FAST_LIO
WORKDIR /root/limx_ws
RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    apt update && \
    cd src/ && \
    git clone https://github.com/Ericsii/FAST_LIO.git --recursive && \
    cd /root/limx_ws && \
    [ -f /etc/ros/rosdep/sources.list.d/20-default.list ] || rosdep init && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -y --skip-keys='livox_sdk2' && \
    colcon build --symlink-install --packages-select fast_lio && \
    source install/setup.bash"

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
